/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x
/usr/bin/time -a -o tim ./run.x

